'site_name': 'Tanssi Docs'
'site_url': 'https://docs.tanssi.network/'
'home_url': 'https://tanssi.network/'
'site_dir': '/var/www/tanssi-docs-static'
'docs_dir': 'tanssi-docs'
'copyright': '© 2024 Moondance Labs. All Rights Reserved.'
'extra_javascript':
  - 'js/externalLinkModal.js'
  - 'js/fixCreatedDate.js'
'extra_css':
  - '/assets/stylesheets/tanssi.css'
  - '/assets/stylesheets/extra.css'
  - '/assets/stylesheets/termynal.css'
'theme':
  'name': 'material'
  'custom_dir': 'material-overrides'
  'favicon': '/assets/images/tanssi-favicon.webp'
  'logo': '/assets/images/tanssi-logo-black.webp'
  'logo_dark_mode': '/assets/images/tanssi-logo-white.webp'
  'font':
    'text': 'Inter'
  'features':
    - 'navigation.tabs'
    - 'navigation.tabs.sticky'
    - 'navigation.sections'
    - 'navigation.indexes'
    - 'navigation.instant'
    - 'content.code.copy'
  'palette':
    # Palette toggle for light mode
    - 'media': '(prefers-color-scheme: light)'
      'scheme': default
      'toggle':
        'icon': material/weather-night
        'name': Switch to dark mode
    # Palette toggle for dark mode
    - 'media': '(prefers-color-scheme: dark)'
      'scheme': slate
      'toggle':
        'icon': material/weather-sunny
        'name': Switch to light mode
'markdown_extensions':
  - 'admonition'
  - 'attr_list'
  - 'codehilite'
  - 'meta'
  - 'pymdownx.details'
  - 'pymdownx.emoji':
      'emoji_index': !!python/name:material.extensions.emoji.twemoji
      'emoji_generator': !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - 'pymdownx.snippets':
      'base_path': 'tanssi-docs/.snippets'
  - 'pymdownx.superfences'
  - 'pymdownx.tabbed':
      'alternate_style': !!bool 'true'
  - 'toc':
      'permalink': !!bool 'true'
      'title': 'Sections'
'validation':
  'absolute_links': 'ignore'
  'unrecognized_links': 'ignore'
'exclude_docs': 'README.md'
'plugins':
  - include-markdown
  - 'search'
  - 'awesome-pages'
  - 'git-revision-date-localized':
      'enable_creation_date': !!bool 'true'
  - 'minify':
      'minify_html': !!bool 'true'
      'minify_js': !!bool 'true'
      'minify_css': !!bool 'true'
      'js_files':
        - 'js/externalLinkModal.js'
        - 'js/fixCreatedDate.js'
      'css_files': 
        # - '/assets/stylesheets/tanssi.css'
        # - '/assets/stylesheets/extra.css'
        # - '/assets/stylesheets/termynal.css'
  - 'redirects':
      'redirect_maps':
        # Redirects will go here as pages get moved around in the following format:
        # 'old-page.md': 'new-page.md'
        'builders/deploy-manage/dapp/deploy.md': 'builders/deploy/dapp.md'
        'builders/deploy-manage/dapp/index.md': 'builders/deploy/index.md'
        'builders/interact/ethereum-api/dev-env/index.md': 'builders/toolkit/ethereum-api/dev-env/index.md'
        'builders/interact/ethereum-api/dev-env/foundry.md': 'builders/toolkit/ethereum-api/dev-env/foundry.md'
        'builders/interact/ethereum-api/dev-env/hardhat.md': 'builders/toolkit/ethereum-api/dev-env/hardhat.md'
        'builders/interact/ethereum-api/dev-env/remix.md': 'builders/toolkit/ethereum-api/dev-env/remix.md'
        'builders/interact/ethereum-api/index.md': 'builders/toolkit/ethereum-api/index.md'
        'builders/interact/ethereum-api/indexers/index.md': 'builders/toolkit/integrations/indexers/index.md'
        'builders/interact/ethereum-api/indexers/subsquid/index.md': 'builders/toolkit/integrations/indexers/subsquid/index.md'
        'builders/interact/ethereum-api/libraries/index.md': 'builders/toolkit/ethereum-api/libraries/index.md'
        'builders/interact/ethereum-api/libraries/ethersjs.md': 'builders/toolkit/ethereum-api/libraries/ethersjs.md'
        'builders/interact/ethereum-api/libraries/viem.md': 'builders/toolkit/ethereum-api/libraries/viem.md'
        'builders/interact/ethereum-api/libraries/web3js.md': 'builders/toolkit/ethereum-api/libraries/web3js.md'
        'builders/interact/ethereum-api/libraries/web3py.md': 'builders/toolkit/ethereum-api/libraries/web3py.md'
        'builders/interact/ethereum-api/wallets/index.md': 'builders/toolkit/ethereum-api/wallets/index.md'
        'builders/interact/ethereum-api/wallets/metamask.md': 'builders/toolkit/ethereum-api/wallets/metamask.md'
        'builders/interact/ethereum-api/wallets/subwallet.md': 'builders/toolkit/ethereum-api/wallets/subwallet.md'
        'builders/interact/ethereum-api/wallets/talisman.md': 'builders/toolkit/ethereum-api/wallets/talisman.md'
        'builders/interact/index.md': 'builders/toolkit/index.md'
        'builders/interact/substrate-api/chopsticks.md': 'builders/toolkit/substrate-api/dev-env/chopsticks.md'
        'builders/interact/substrate-api/index.md': 'builders/toolkit/substrate-api/index.md'
        'builders/interact/substrate-api/indexers/index.md': 'builders/toolkit/integrations/indexers/index.md'
        'builders/interact/substrate-api/indexers/subsquid/index.md': 'builders/toolkit/integrations/indexers/subsquid/index.md'
        'builders/interact/substrate-api/polkadot-js-api.md': 'builders/toolkit/substrate-api/libraries/polkadot-js-api.md'
        'builders/interact/substrate-api/sidecar-api.md': 'builders/toolkit/substrate-api/libraries/sidecar-api.md'
        'builders/interact/substrate-api/wallets/index.md': 'builders/toolkit/substrate-api/wallets/index.md'
        'builders/interact/substrate-api/wallets/subwallet.md': 'builders/toolkit/substrate-api/wallets/subwallet.md'
        'builders/interact/substrate-api/wallets/talisman.md': 'builders/toolkit/substrate-api/wallets/talisman.md'
        'builders/tanssi-network/networks/index.md': 'builders/tanssi-network/index.md'
        'builders/tanssi-network/networks/dancebox/demo-evm-containerchain.md': 'builders/tanssi-network/testnet/demo-evm-appchain.md'
        'builders/tanssi-network/networks/dancebox/index.md': 'builders/tanssi-network/testnet/dancebox.md'
        'builders/tanssi-network/networks/dancebox/overview.md': 'builders/tanssi-network/testnet/dancebox.md'
        'builders/tooling/index.md': 'builders/toolkit/integrations/index.md'
        'builders/tooling/indexers/index.md': 'builders/toolkit/integrations/indexers/index.md'
        'builders/tooling/indexers/subsquid.md': 'builders/toolkit/integrations/indexers/subsquid/index.md'
        'builders/tooling/oracles/acurast.md': 'builders/toolkit/integrations/oracles/acurast.md'
        'builders/tooling/oracles/index.md': 'builders/toolkit/integrations/oracles/index.md'
        'builders/tooling/oracles/phala.md': 'builders/toolkit/integrations/oracles/phala.md'
        'builders/tutorials/index.md': 'builders/toolkit/integrations/index.md'
        'builders/tutorials/subsquid.md': 'builders/toolkit/integrations/indexers/subsquid/erc20-transfers.md'
        'dapp-developers/developer-toolkit/ethereum-api/dev-env/index.md': 'builders/toolkit/ethereum-api/dev-env/index.md'
        'dapp-developers/developer-toolkit/ethereum-api/dev-env/foundry.md': 'builders/toolkit/ethereum-api/dev-env/foundry.md'
        'dapp-developers/developer-toolkit/ethereum-api/dev-env/hardhat.md': 'builders/toolkit/ethereum-api/dev-env/hardhat.md'
        'dapp-developers/developer-toolkit/ethereum-api/dev-env/remix.md': 'builders/toolkit/ethereum-api/dev-env/remix.md'
        'dapp-developers/developer-toolkit/ethereum-api/index.md': 'builders/toolkit/ethereum-api/index.md'
        'dapp-developers/developer-toolkit/ethereum-api/libraries/ethersjs.md': 'builders/toolkit/ethereum-api/libraries/ethersjs.md'
        'dapp-developers/developer-toolkit/ethereum-api/libraries/index.md': 'builders/toolkit/ethereum-api/libraries/index.md'
        'dapp-developers/developer-toolkit/ethereum-api/libraries/viem.md': 'builders/toolkit/ethereum-api/libraries/viem.md'
        'dapp-developers/developer-toolkit/ethereum-api/libraries/web3js.md': 'builders/toolkit/ethereum-api/libraries/web3js.md'
        'dapp-developers/developer-toolkit/ethereum-api/libraries/web3py.md': 'builders/toolkit/ethereum-api/libraries/web3py.md'
        'dapp-developers/developer-toolkit/ethereum-api/wallets/index.md': 'builders/toolkit/ethereum-api/wallets/index.md'
        'dapp-developers/developer-toolkit/ethereum-api/wallets/metamask.md': 'builders/toolkit/ethereum-api/wallets/metamask.md'
        'dapp-developers/developer-toolkit/ethereum-api/wallets/subwallet.md': 'builders/toolkit/ethereum-api/wallets/subwallet.md'
        'dapp-developers/developer-toolkit/ethereum-api/wallets/talisman.md': 'builders/toolkit/ethereum-api/wallets/talisman.md'
        'dapp-developers/developer-toolkit/substrate-api/chopsticks.md': 'builders/toolkit/substrate-api/dev-env/chopsticks.md'
        'dapp-developers/developer-toolkit/substrate-api/index.md': 'builders/toolkit/substrate-api/index.md'
        'dapp-developers/developer-toolkit/substrate-api/polkadot-js-api.md': 'builders/toolkit/substrate-api/libraries/polkadot-js-api.md'
        'dapp-developers/developer-toolkit/substrate-api/sidecar-api.md': 'builders/toolkit/substrate-api/libraries/sidecar-api.md'
        'dapp-developers/developer-toolkit/substrate-api/wallets/index.md': 'builders/toolkit/substrate-api/wallets/index.md'
        'dapp-developers/developer-toolkit/substrate-api/wallets/subwallet.md': 'builders/toolkit/substrate-api/wallets/subwallet.md'
        'dapp-developers/developer-toolkit/substrate-api/wallets/talisman.md': 'builders/toolkit/substrate-api/wallets/talisman.md'
        'dapp-developers/index.md': 'builders/toolkit/index.md'
        'dapp-developers/integrations/index.md': 'builders/toolkit/integrations/index.md'
        'dapp-developers/integrations/indexers/index.md': 'builders/toolkit/integrations/indexers/index.md'
        'dapp-developers/integrations/indexers/subsquid/index.md': 'builders/toolkit/integrations/indexers/subsquid/index.md'
        'dapp-developers/integrations/indexers/subsquid/quick-start.md': 'builders/toolkit/integrations/indexers/subsquid/quick-start.md'
        'dapp-developers/integrations/indexers/subsquid/quick-start.md': 'builders/toolkit/integrations/indexers/subsquid/erc20-transfers.md'
        'dapp-developers/integrations/oracles/acurast.md': 'builders/toolkit/integrations/oracles/acurast.md'
        'dapp-developers/integrations/oracles/index.md': 'builders/toolkit/integrations/oracles/index.md'
        'dapp-developers/integrations/oracles/phala.md': 'builders/toolkit/integrations/oracles/phala.md'
        'node-operators/block-producers/onboarding/proxy-accounts.md': 'node-operators/block-producers/operational-tasks/proxy-accounts.md'
  - 'macros':
      'include_yaml':
        - 'tanssi-docs/variables.yml'
'extra':
  'generator': !!bool 'false'
  'social':
    - 'icon': 'fontawesome/brands/discord'
      'link': 'https://discord.gg/kuyPhew2KB'
      'name': 'Discord'
    - 'icon': 'fontawesome/brands/telegram'
      'link': 'https://t.me/tanssiofficial'
      'name': 'Telegram'
    - 'icon': 'fontawesome/brands/twitter'
      'link': 'https://twitter.com/TanssiNetwork'
      'name': 'Twitter'
    - 'icon': 'fontawesome/brands/github'
      'link': 'https://github.com/moondance-labs/tanssi'
      'name': 'GitHub'
  'analytics':
    'provider': 'google'
    'property': 'G-BT4KVVBH8F'
    'feedback':
      'title': 'Was this page helpful?'
      'ratings':
        - 'icon': 'material/emoticon-happy-outline'
          'name': 'This page was helpful'
          'data': 1
          'note': >-
            Thanks for your feedback!
        - 'icon': 'material/emoticon-sad-outline'
          'name': 'This page could be improved'
          'data': 0
          'note': >-
            Thanks for your feedback! Help us improve this page by submitting
            <a href="https://github.com/moondance-labs/tanssi-docs/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">additional feedback</a>.
