name: Deploy Docs
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build and deploy documentation from"
        required: true
        default: "main"
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache 
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - name: Debug Paths
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "Site Directory: $GITHUB_WORKSPACE/site"
          echo "Docs Directory: $GITHUB_WORKSPACE/tanssi-docs"
          echo "Current Directory: $(pwd)"
          echo "Contents of tanssi-docs:"
          ls -la "$GITHUB_WORKSPACE/tanssi-docs"
          echo "Contents of site:"
          ls -la "$GITHUB_WORKSPACE/site"
      - name: Deploy Docs
        run: |
          mkdocs gh-deploy --force \
            --site-dir "$GITHUB_WORKSPACE/site" 
